// Dynamic Tenders Data generated by crawler.py
window.tendersLastUpdated = '2026/09/18 01:20';
window.tendersAwardData = [
  {
    "id": 1,
    "title": "影印機租賃",
    "agency": "衛生福利部屏東醫院",
    "location": "屏東",
    "budget": "224.8 萬",
    "awardAmount": "224.6 萬",
    "basePrice": "224.8 萬",
    "date": "115/08/19",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260917&fn=BDM-1-71284713.xml"
  },
  {
    "id": 2,
    "title": "藥袋印表機碳粉匣及墨水匣(提供儀器) (開口契約)",
    "agency": "屏東榮民總醫院",
    "location": "屏東",
    "budget": "未定",
    "awardAmount": "未定",
    "basePrice": "未定",
    "date": "115/09/17",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260917&fn=BDM-1-71285391.xml"
  },
  {
    "id": 3,
    "title": "新北市立聯合醫院「列印（印表機租賃）服務」採購案",
    "agency": "新北市立聯合醫院",
    "location": "新北",
    "budget": "未定",
    "awardAmount": "未定",
    "basePrice": "未定",
    "date": "115/09/17",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260917&fn=BDM-1-71285204.xml"
  },
  {
    "id": 4,
    "title": "115~118年印表機墨水匣採購案",
    "agency": "衛生福利部新營醫院",
    "location": "未知",
    "budget": "未定",
    "awardAmount": "未定",
    "basePrice": "未定",
    "date": "115/09/15",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260915&fn=anaa-71284589.xml"
  },
  {
    "id": 5,
    "title": "「核心帳務主機高速中英文雷射連續式印表機2年維護」採購案",
    "agency": "臺灣銀行股份有限公司",
    "location": "未知",
    "budget": "未定",
    "awardAmount": "未定",
    "basePrice": "未定",
    "date": "115/09/11",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260911&fn=BDM-1-71280144.xml"
  },
  {
    "id": 6,
    "title": "「114年至115年度數位式影印機租賃採購案」後續擴充",
    "agency": "財政部關務署臺北關",
    "location": "桃園",
    "budget": "176.4 萬",
    "awardAmount": "164.1 萬",
    "basePrice": "176.4 萬",
    "date": "115/08/21",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260909&fn=BDM-1-71278799.xml"
  }
];
window.tendersData = [
  {
    "id": 1,
    "category": "事務機",
    "title": "總管理處數位式多功能影印機租賃共61台",
    "agency": "台灣電力股份有限公司",
    "location": "台北",
    "budget": "644.7 萬",
    "deadline": "10/02",
    "days": 69,
    "priority": "高",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260918&fn=TIQ-1-71117547.xml",
    "details": "*****押標金特別注意事項***** *以電匯或線上方式繳納押標金，申請押標金發還需行政作業時間，請廠商自 行衡量作業時間。 *以票據方式繳納押標金，若不克親自前來開標現場領回押標金票據，建議可於標封內付[掛號郵寄退還押標金票據切結書]，以加速押標金票據退還作業。 *****其他附加說明***** 1. 上述金額均含5%營業稅，本案不含營業稅之採購金額：新臺幣7,675,000 元/不含營業稅預算金額：新臺幣6,140,000元。 2. 廠商標價或報價金額超過預算金額者，為不合格標，不予減價機會。 3. 標封內未附招標文件所規定之資格證明文件，或經審查結果證件內容不 符，或時效已過等不合規定...",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "依全台歷史類似案平均折扣率 90.0% 推算，本案預估合理得標折數區間為 90% - 94%。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": []
  },
  {
    "id": 2,
    "category": "事務機",
    "title": "115學年度影印機租賃",
    "agency": "苗栗縣立新港國民中小學",
    "location": "苗栗",
    "budget": "35 萬",
    "deadline": "09/23",
    "days": 60,
    "priority": "中",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260918&fn=ttd-71331618.xml",
    "details": "未達公告金額之採購，爭議屬政府採購法第31條規定不予發還或追繳押標金之爭議，始得提出申訴。",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "依全台歷史類似案平均折扣率 90.0% 推算，本案預估合理得標折數區間為 87% - 91%。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": []
  },
  {
    "id": 3,
    "category": "事務機",
    "title": "影印機租賃公開徵求共同供應契約廠商遴選會議",
    "agency": "經濟部水利署",
    "location": "未知",
    "budget": "未定",
    "deadline": "未公告",
    "days": 5,
    "priority": "低",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260917&fn=PPW-2-70116483.xml",
    "details": "尚無詳細商機說明。",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "依全台歷史類似案平均折扣率 90.0% 推算，本案預估合理得標折數區間為 87% - 91%。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": []
  },
  {
    "id": 4,
    "category": "事務機",
    "title": "展覽中心『展覽大樓「冷凍空調、事務機、顯示器及影像分析處理設備等報廢財物1批」』",
    "agency": "財團法人中華民國對外貿易發展協會",
    "location": "未知",
    "budget": "未定",
    "deadline": "未公告",
    "days": 5,
    "priority": "低",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260915&fn=FAS-1-70020753.xml",
    "details": "尚無詳細商機說明。",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "依全台歷史類似案平均折扣率 90.0% 推算，本案預估合理得標折數區間為 86% - 90%。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": []
  },
  {
    "id": 5,
    "category": "事務機",
    "title": "印表機維護案",
    "agency": "國防部電訊發展室",
    "location": "未知",
    "budget": "未定",
    "deadline": "未公告",
    "days": 5,
    "priority": "低",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260915&fn=PPW-1-70116236.xml",
    "details": "尚無詳細商機說明。",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "依全台歷史類似案平均折扣率 90.0% 推算，本案預估合理得標折數區間為 87% - 91%。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": []
  }
];
