// Dynamic Tenders Data generated by crawler.py
window.tendersLastUpdated = '2026/09/13 01:14';
window.tendersAwardData = [
  {
    "id": 1,
    "title": "「核心帳務主機高速中英文雷射連續式印表機2年維護」採購案",
    "agency": "臺灣銀行股份有限公司",
    "location": "未知",
    "budget": "未定",
    "awardAmount": "未定",
    "basePrice": "未定",
    "date": "115/09/11",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260911&fn=BDM-1-71280144.xml"
  },
  {
    "id": 2,
    "title": "「114年至115年度數位式影印機租賃採購案」後續擴充",
    "agency": "財政部關務署臺北關",
    "location": "桃園",
    "budget": "176.4 萬",
    "awardAmount": "164.1 萬",
    "basePrice": "176.4 萬",
    "date": "115/08/21",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260909&fn=BDM-1-71278799.xml"
  },
  {
    "id": 3,
    "title": "藥袋印表機碳粉匣及墨水匣(提供儀器) (開口契約)",
    "agency": "屏東榮民總醫院",
    "location": "屏東",
    "budget": "未定",
    "awardAmount": "未定",
    "basePrice": "未定",
    "date": "115/09/09",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260909&fn=NAI-1-71278296.xml"
  },
  {
    "id": 4,
    "title": "新北市立聯合醫院「列印（印表機租賃）服務」採購案",
    "agency": "新北市立聯合醫院",
    "location": "新北",
    "budget": "未定",
    "awardAmount": "未定",
    "basePrice": "未定",
    "date": "115/09/07",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260907&fn=NAI-1-71276049.xml"
  },
  {
    "id": 5,
    "title": "115年行列式印表機汰換案",
    "agency": "花蓮縣地方稅務局",
    "location": "花蓮",
    "budget": "未定",
    "awardAmount": "未定",
    "basePrice": "未定",
    "date": "115/09/07",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260907&fn=anaa-71277454.xml"
  },
  {
    "id": 6,
    "title": "臺大醫療體系黑白及彩色影印機租賃單價合約1式",
    "agency": "國立臺灣大學醫學院附設醫院",
    "location": "未知",
    "budget": "未定",
    "awardAmount": "未定",
    "basePrice": "未定",
    "date": "115/09/01",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260901&fn=BDM-1-71271477.xml"
  }
];
window.tendersData = [
  {
    "id": 1,
    "category": "事務機",
    "title": "新北市立聯合醫院「列印（印表機租賃）服務」採購案",
    "agency": "新北市立聯合醫院",
    "location": "新北",
    "budget": "1467.6 萬",
    "deadline": "09/03",
    "days": 40,
    "priority": "高",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260911&fn=TIQ-1-71112845.xml",
    "details": "尚無詳細商機說明。",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "參考本案機關歷史前案折扣率 97.6%，預估得標區間為 96% - 100%。需防範對手低價搶標。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": [
      {
        "title": "新北市立聯合醫院超融合設備維護案",
        "agency": "新北市立聯合醫院",
        "date": "114/01/24",
        "budget": "278.8 萬",
        "awardAmount": "272 萬",
        "basePrice": "278 萬",
        "ratio": "97.6%",
        "ratioNum": 97.5609756097561
      }
    ]
  },
  {
    "id": 2,
    "category": "事務機",
    "title": "115年印表機租賃(開口契約)",
    "agency": "高雄市立凱旋醫院",
    "location": "高雄",
    "budget": "518.4 萬",
    "deadline": "09/29",
    "days": 66,
    "priority": "高",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260911&fn=TIQ-1-71112735.xml",
    "details": "尚無詳細商機說明。",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "參考本案機關歷史前案折扣率 98.1%，預估得標區間為 94% - 98%。需防範對手低價搶標。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": [
      {
        "title": "「高雄市立凱旋醫院醫療園區植栽維護」(後續擴充)",
        "agency": "高雄市立凱旋醫院",
        "date": "115/01/16",
        "budget": "190 萬",
        "awardAmount": "190 萬",
        "basePrice": "未定",
        "ratio": "100.0%",
        "ratioNum": 100.0
      },
      {
        "title": "高雄市立凱旋醫院醫療園區植栽維護",
        "agency": "高雄市立凱旋醫院",
        "date": "114/03/14",
        "budget": "200.3 萬",
        "awardAmount": "190 萬",
        "basePrice": "190 萬",
        "ratio": "94.9%",
        "ratioNum": 94.85771342985522
      },
      {
        "title": "高雄市立凱旋醫院醫療園區植栽維護",
        "agency": "高雄市立凱旋醫院",
        "date": "112/12/28",
        "budget": "149.0 萬",
        "awardAmount": "148 萬",
        "basePrice": "148 萬",
        "ratio": "99.3%",
        "ratioNum": 99.32885906040269
      }
    ]
  },
  {
    "id": 3,
    "category": "事務機",
    "title": "印表機原廠耗材",
    "agency": "臺灣銀行股份有限公司",
    "location": "未知",
    "budget": "未定",
    "deadline": "未公告",
    "days": 5,
    "priority": "低",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260911&fn=PPW-1-70115977.xml",
    "details": "尚無詳細商機說明。",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "參考本案機關歷史前案折扣率 93.9%，預估得標區間為 92% - 96%。需防範對手低價搶標。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": [
      {
        "title": "臺灣銀行股份有限公司廣州分行2026年機房弱電設備維護",
        "agency": "臺灣銀行股份有限公司",
        "date": "115/08/31",
        "budget": "20.2 萬",
        "awardAmount": "18 萬",
        "basePrice": "18 萬",
        "ratio": "89.1%",
        "ratioNum": 89.10891089108911
      },
      {
        "title": "臺灣銀行股份有限公司香港分行2026年度FTS主機設備系統維護續約案",
        "agency": "臺灣銀行股份有限公司",
        "date": "115/05/20",
        "budget": "22.8 萬",
        "awardAmount": "22.8 萬",
        "basePrice": "22.8 萬",
        "ratio": "100.0%",
        "ratioNum": 100.0
      },
      {
        "title": "臺灣銀行股份有限公司廣州分行公務車租賃採購案",
        "agency": "臺灣銀行股份有限公司",
        "date": "115/05/15",
        "budget": "44.3 萬",
        "awardAmount": "41.0 萬",
        "basePrice": "41.4 萬",
        "ratio": "92.6%",
        "ratioNum": 92.55079006772009
      }
    ]
  },
  {
    "id": 4,
    "category": "事務機",
    "title": "二手影印機租賃",
    "agency": "臺灣銀行股份有限公司",
    "location": "未知",
    "budget": "未定",
    "deadline": "未公告",
    "days": 5,
    "priority": "低",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260909&fn=PPW-1-70115536.xml",
    "details": "尚無詳細商機說明。",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "參考本案機關歷史前案折扣率 93.9%，預估得標區間為 92% - 96%。需防範對手低價搶標。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": [
      {
        "title": "臺灣銀行股份有限公司廣州分行2026年機房弱電設備維護",
        "agency": "臺灣銀行股份有限公司",
        "date": "115/08/31",
        "budget": "20.2 萬",
        "awardAmount": "18 萬",
        "basePrice": "18 萬",
        "ratio": "89.1%",
        "ratioNum": 89.10891089108911
      },
      {
        "title": "臺灣銀行股份有限公司香港分行2026年度FTS主機設備系統維護續約案",
        "agency": "臺灣銀行股份有限公司",
        "date": "115/05/20",
        "budget": "22.8 萬",
        "awardAmount": "22.8 萬",
        "basePrice": "22.8 萬",
        "ratio": "100.0%",
        "ratioNum": 100.0
      },
      {
        "title": "臺灣銀行股份有限公司廣州分行公務車租賃採購案",
        "agency": "臺灣銀行股份有限公司",
        "date": "115/05/15",
        "budget": "44.3 萬",
        "awardAmount": "41.0 萬",
        "basePrice": "41.4 萬",
        "ratio": "92.6%",
        "ratioNum": 92.55079006772009
      }
    ]
  },
  {
    "id": 5,
    "category": "事務機",
    "title": "115-117年單張式／連續式印表機列印藥袋張數採購案（附使用之印表機及相關耗材",
    "agency": "臺北市立聯合醫院",
    "location": "台北",
    "budget": "499.2 萬",
    "deadline": "09/22",
    "days": 59,
    "priority": "高",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260909&fn=TIQ-1-71111090.xml",
    "details": "招標規格請洽藥劑部楊鴻恩先生 (02)2555-3000轉2794 1.專人領購：請於截止收件期限辦公時間內親至台北市10851萬華區艋舺大道101號11樓(總務室採購供應股)洽購，每份新台幣貳佰元整。 2.函購：工本費貳佰元，自備回郵及信封，郵寄封面註明「購領xx文件」字樣，並請自行考量郵遞時程。 3.電子領標：請連線至網址http：//www.geps.gov.tw/下載標單。 [收受投標文件地點]：台北市10851萬華區艋舺大道101號11樓(收發室)郵寄報價單（標單）者,請自行計算並注意截止收件期限,超過期限不予受理 4.履約保證金：新臺幣20萬元(同押標金) 5.預定決標日為開標日 ...",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "依全台歷史類似案平均折扣率 90.0% 推算，本案預估合理得標折數區間為 86% - 90%。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": []
  },
  {
    "id": 6,
    "category": "事務機",
    "title": "藥袋印表機碳粉匣及墨水匣(提供儀器) (開口契約)",
    "agency": "屏東榮民總醫院",
    "location": "屏東",
    "budget": "1282.6 萬",
    "deadline": "07/30",
    "days": 5,
    "priority": "高",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260909&fn=TIQ-1-71110888.xml",
    "details": "尚無詳細商機說明。",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "參考本案機關歷史前案折扣率 99.5%，預估得標區間為 96% - 100%。需防範對手低價搶標。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": [
      {
        "title": "屏東榮民總醫院龍泉分院停車場維護合約",
        "agency": "屏東榮民總醫院",
        "date": "115/07/15",
        "budget": "21.6 萬",
        "awardAmount": "21.5 萬",
        "basePrice": "21.5 萬",
        "ratio": "99.5%",
        "ratioNum": 99.53703703703704
      }
    ]
  }
];
