// Dynamic Tenders Data generated by crawler.py
window.tendersLastUpdated = '2026/09/08 01:16';
window.tendersAwardData = [
  {
    "id": 1,
    "title": "115年行列式印表機汰換案",
    "agency": "花蓮縣地方稅務局",
    "location": "花蓮",
    "budget": "未定",
    "awardAmount": "未定",
    "basePrice": "未定",
    "date": "115/09/07",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260907&fn=anaa-71277454.xml"
  },
  {
    "id": 2,
    "title": "新北市立聯合醫院「列印（印表機租賃）服務」採購案",
    "agency": "新北市立聯合醫院",
    "location": "新北",
    "budget": "未定",
    "awardAmount": "未定",
    "basePrice": "未定",
    "date": "115/09/07",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260907&fn=NAI-1-71276049.xml"
  },
  {
    "id": 3,
    "title": "臺大醫療體系黑白及彩色影印機租賃單價合約1式",
    "agency": "國立臺灣大學醫學院附設醫院",
    "location": "未知",
    "budget": "未定",
    "awardAmount": "未定",
    "basePrice": "未定",
    "date": "115/09/01",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260901&fn=BDM-1-71271477.xml"
  },
  {
    "id": 4,
    "title": "A5門診系統雷射印表機空白紙二年單價開口契約",
    "agency": "臺北榮民總醫院",
    "location": "台北",
    "budget": "789.6 萬",
    "awardAmount": "602.1 萬",
    "basePrice": "602.1 萬",
    "date": "115/08/27",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260828&fn=BDM-1-71269777.xml"
  },
  {
    "id": 5,
    "title": "高速行列式印表機",
    "agency": "考選部",
    "location": "台北",
    "budget": "24 萬",
    "awardAmount": "23.2 萬",
    "basePrice": "23.2 萬",
    "date": "115/08/21",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260827&fn=BDM-1-71267854.xml"
  },
  {
    "id": 6,
    "title": "115年度KYOCERA雷射印表機耗材採購案",
    "agency": "財政部北區國稅局",
    "location": "桃園",
    "budget": "405.9 萬",
    "awardAmount": "401.9 萬",
    "basePrice": "405 萬",
    "date": "115/08/19",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260826&fn=BDM-1-71266460.xml"
  }
];
window.tendersData = [
  {
    "id": 1,
    "category": "事務機",
    "title": "115年地方公職人員選舉雷射印表機耗材",
    "agency": "高雄市選舉委員會",
    "location": "高雄",
    "budget": "206.0 萬",
    "deadline": "09/18",
    "days": 55,
    "priority": "高",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260908&fn=TIQ-1-71109322.xml",
    "details": "1、投標文件之截止日及開標日倘遇本會因故停止辦公，分別依原訂日期，順延至次一辦公日之同一時間(本會不另通知)。 2、電子領標之廠商以書面投標時，應檢附主管機關指定資訊系統之領標電子憑據。",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "依全台歷史類似案平均折扣率 90.0% 推算，本案預估合理得標折數區間為 90% - 94%。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": []
  },
  {
    "id": 2,
    "category": "事務機",
    "title": "第七聯隊印表機租賃",
    "agency": "國防部空軍司令部",
    "location": "未知",
    "budget": "未定",
    "deadline": "未公告",
    "days": 5,
    "priority": "低",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260908&fn=PPW-1-70115361.xml",
    "details": "尚無詳細商機說明。",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "依全台歷史類似案平均折扣率 90.0% 推算，本案預估合理得標折數區間為 90% - 94%。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": []
  },
  {
    "id": 3,
    "category": "事務機",
    "title": "Oce-4650 高速印表機(含周邊設備)供應列印耗材暨維護",
    "agency": "中華郵政股份有限公司臺北郵局",
    "location": "台北",
    "budget": "4102.2 萬",
    "deadline": "10/19",
    "days": 86,
    "priority": "高",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260907&fn=TIQ-1-71107576.xml",
    "details": "1.投標廠商登記或設立之證明文件。如公司登記或商業登記證明文件或其他由政府機關（含其授權機構）核發之合法登記或設立之證明文件等。【註：為因應自98年4月13日起停止使用「營利事業登記證」之規定，投標廠商得透過經濟部（http://gcis.nat.gov.tw/index.jsp 商工登記資料）或各直轄市、縣（市）政府資訊網站查詢相關證明資料，並得列印該等資料代之。（營利事業登記證，已不得作為廠商登記或設立之證明文件）】 2.最近1期納稅證明文件。（如不及提出最近1期證明者，得以前1期之納稅證明代之。新設立且未屆第1期營業稅繳納期限者，得以營業稅主管稽徵機關核發之核准設立登記公函代之；經核定使...",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "依全台歷史類似案平均折扣率 90.0% 推算，本案預估合理得標折數區間為 86% - 90%。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": []
  },
  {
    "id": 4,
    "category": "事務機",
    "title": "Canon VS 4650 高速印表機(含周邊設備)供應列印耗材暨維護",
    "agency": "中華郵政股份有限公司臺北郵局",
    "location": "台北",
    "budget": "1677.1 萬",
    "deadline": "10/19",
    "days": 86,
    "priority": "高",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260907&fn=TIQ-1-71107584.xml",
    "details": "1.投標廠商登記或設立之證明文件。如公司登記或商業登記證明文件或其他由政府機關（含其授權機構）核發之合法登記或設立之證明文件等。【註：為因應自98年4月13日起停止使用「營利事業登記證」之規定，投標廠商得透過經濟部（http://gcis.nat.gov.tw/index.jsp 商工登記資料）或各直轄市、縣（市）政府資訊網站查詢相關證明資料，並得列印該等資料代之。（營利事業登記證，已不得作為廠商登記或設立之證明文件）】 2.最近1期納稅證明文件。（如不及提出最近1期證明者，得以前1期之納稅證明代之。新設立且未屆第1期營業稅繳納期限者，得以營業稅主管稽徵機關核發之核准設立登記公函代之；經核定使...",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "依全台歷史類似案平均折扣率 90.0% 推算，本案預估合理得標折數區間為 86% - 90%。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": []
  },
  {
    "id": 5,
    "category": "事務機",
    "title": "116-117年影印機租賃（內含裝機、運費、維修、印量張數價金計算）",
    "agency": "海洋委員會海巡署南部分署",
    "location": "未知",
    "budget": "未定",
    "deadline": "未公告",
    "days": 5,
    "priority": "低",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260904&fn=PPW-1-70115152.xml",
    "details": "尚無詳細商機說明。",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "依全台歷史類似案平均折扣率 90.0% 推算，本案預估合理得標折數區間為 90% - 94%。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": []
  },
  {
    "id": 6,
    "category": "事務機",
    "title": "藥袋印表機碳粉匣及墨水匣(提供儀器) (開口契約)",
    "agency": "屏東榮民總醫院",
    "location": "屏東",
    "budget": "1282.6 萬",
    "deadline": "07/30",
    "days": 5,
    "priority": "高",
    "sourceUrl": "https://web.pcc.gov.tw/prkms/tender/common/noticeDate/redirectPublic?ds=20260902&fn=TIQ-1-71105241.xml",
    "details": "尚無詳細商機說明。",
    "aiCompetitor": "主要競爭對手為台灣佳能 (Canon) 與夏普 (Sharp)，兩者在此類公務機關多以租賃月租費與單張抄表費用折扣進行價格戰。",
    "aiTargetPrice": "參考本案機關歷史前案折扣率 99.5%，預估得標區間為 96% - 100%。需防範對手低價搶標。 建議同仁提出符合大印量的合理標準合約，避免捲入無謂殺價。",
    "historyRecords": [
      {
        "title": "屏東榮民總醫院龍泉分院停車場維護合約",
        "agency": "屏東榮民總醫院",
        "date": "115/07/15",
        "budget": "21.6 萬",
        "awardAmount": "21.5 萬",
        "basePrice": "21.5 萬",
        "ratio": "99.5%",
        "ratioNum": 99.53703703703704
      }
    ]
  }
];
